### ISSUE TITLE
【非Issues！讨论帖】通过lora微调的qianwen和直接使用system来预设的区别貌似不是很大

### ISSUE THREAD

**Issue by Roger-G** [datawhalechina/self-llm#100]
使用04-Qwen-7B-Chat Lora微调方法训练完成后，重新载入，再不预设system的情况下，依然返回自己是千问大模型
![image](https://github.com/datawhalechina/self-llm/assets/37508579/48852033-19b3-48ab-a1a9-e397ef819a4d)
想知道是不是训练不够啊

**Comment by WEXIJUE** [comment]
作者您好，现在还能进群吗？非常感谢！
