### ISSUE TITLE
Qwen1.5-7B Lora微调报错

### ISSUE THREAD

**Issue by JeckerWen** [datawhalechina/self-llm#107]
Qwen1.5-7B Lora微调，报这个错怎么解决啊：ValueError: Target modules {'k_proj', 'gate_proj', 'q_proj', 'down_proj', 'o_proj', 'up_proj', 'v_proj'} not found in the base model.

**Comment by KMnO4-zx** [comment]
检查一下模型是否加载正确，按理说不应该出现这个报错

**Comment by JeckerWen** [comment]
已经解决了哈 谢谢
