### ISSUE TITLE
使用阿里云部署glm-4-9b api报gpu内存不足

### ISSUE THREAD

**Issue by eagleLiu82** [datawhalechina/self-llm#169]
按步骤用的是GPU 24G,但是使用时提示GPU内存不足

**Comment by YuanshuaiHuang** [comment]
可以提供一些截图和阿里云设备信息，方便我们复现

**Comment by eagleLiu82** [comment]
> 可以提供一些截图和阿里云设备信息，方便我们复现

![2](https://github.com/datawhalechina/self-llm/assets/20007468/ebec354f-8324-443b-9143-24cdc8492c4b)
![1](https://github.com/datawhalechina/self-llm/assets/20007468/09966cf3-b1e6-4f69-81de-350144bae22c)

**Comment by eagleLiu82** [comment]
使用curl访问时报错

**Comment by eagleLiu82** [comment]
这个问题也解决了，不能重复跑，要重新打开notebook，
应该是占用的资源没释放。

**Comment by KMnO4-zx** [comment]
嗯嗯 好的。问题解决了，那这个issue就关闭啦～
