### ISSUE TITLE
GLM-4-9B-chat微调过程中，加载Lora权重推理阶段报错ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Eric374254** [datawhalechina/self-llm#198]
在其他部分完全参照GLM4-9B-chat Lora 微调.部分进行的时候均未出现异常，在最后加载Lora进行权重推理之后报错。
显示outputs = model.generate(**inputs, **gen_kwargs)一行出现错误，求大佬帮忙解答
完整报错内容如下：

ValueError                                Traceback (most recent call last)
Cell In[25], line 28
     26 gen_kwargs = {"max_length": 5000, "do_sample": True, "top_k": 1}
     27 with torch.no_grad():
---> 28     outputs = model.generate(**inputs, **gen_kwargs)
     29     outputs = outputs[:, inputs['input_ids'].shape[1]:]
     30     print(tokenizer.decode(outputs[0], skip_special_tokens=True))

File /opt/conda/lib/python3.9/site-packages/peft/peft_model.py:1190, in PeftModelForCausalLM.generate(self, *args, **kwargs)
   1188     with self._enable_peft_forward_hooks(*args, **kwargs):
   1189         kwargs = {k: v for k, v in kwargs.items() if k not in self.special_peft_forward_args}
-> 1190         outputs = self.base_model.generate(*args, **kwargs)
   1191 else:
   1192     outputs = self.base_model.generate(**kwargs)

File /opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File /opt/conda/lib/python3.9/site-packages/transformers/generation/utils.py:1914, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1906     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1907         input_ids=input_ids,
   1908         expand_size=generation_config.num_return_sequences,
   1909         is_encoder_decoder=self.config.is_encoder_decoder,
   1910         **model_kwargs,
   1911     )
   1913     # 13. run sample (it degenerates to greedy search when `generation_config.do_sample=False`)
-> 1914     result = self._sample(
   1915         input_ids,
   1916         logits_processor=prepared_logits_processor,
   1917         logits_warper=prepared_logits_warper,
   1918         stopping_criteria=prepared_stopping_criteria,
   1919         generation_config=generation_config,
   1920         synced_gpus=synced_gpus,
   1921         streamer=streamer,
   1922         **model_kwargs,
   1923     )
   1925 elif generation_mode in (GenerationMode.BEAM_SAMPLE, GenerationMode.BEAM_SEARCH):
   1926     # 11. prepare logits warper
   1927     prepared_logits_warper = (
   1928         self._get_logits_warper(generation_config, device=input_ids.device)
   1929         if generation_config.do_sample
   1930         else None
   1931     )

File /opt/conda/lib/python3.9/site-packages/transformers/generation/utils.py:2651, in GenerationMixin._sample(self, input_ids, logits_processor, stopping_criteria, generation_config, synced_gpus, streamer, logits_warper, **model_kwargs)
   2648 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
   2650 # forward pass to get next token
-> 2651 outputs = self(
   2652     **model_inputs,
   2653     return_dict=True,
   2654     output_attentions=output_attentions,
   2655     output_hidden_states=output_hidden_states,
   2656 )
   2658 if synced_gpus and this_peer_finished:
   2659     continue  # don't waste resources running the code we don't need

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File ~/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py:878, in ChatGLMForConditionalGeneration.forward(self, input_ids, position_ids, attention_mask, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict, return_last_logit)
    875 use_cache = use_cache if use_cache is not None else self.config.use_cache
    876 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
--> 878 transformer_outputs = self.transformer(
    879     input_ids=input_ids,
    880     position_ids=position_ids,
    881     attention_mask=attention_mask,
    882     past_key_values=past_key_values,
    883     inputs_embeds=inputs_embeds,
    884     use_cache=use_cache,
    885     output_hidden_states=output_hidden_states,
    886     return_dict=return_dict,
    887 )
    889 hidden_states = transformer_outputs[0]
    890 if return_last_logit:

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File ~/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py:774, in ChatGLMModel.forward(self, input_ids, position_ids, attention_mask, full_attention_mask, past_key_values, inputs_embeds, use_cache, output_hidden_states, return_dict)
    771     rotary_pos_emb = rotary_pos_emb[None, :seq_length]
    773 # Run encoder.
--> 774 hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
    775     inputs_embeds, full_attention_mask, rotary_pos_emb=rotary_pos_emb,
    776     kv_caches=past_key_values, use_cache=use_cache, output_hidden_states=output_hidden_states
    777 )
    778 if presents is not None and type(presents) is torch.Tensor:
    779     presents = presents.split(1, dim=0)

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File ~/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py:607, in GLMTransformer.forward(self, hidden_states, attention_mask, rotary_pos_emb, kv_caches, use_cache, output_hidden_states)
    597     layer_ret = torch.utils.checkpoint.checkpoint(
    598         layer,
    599         hidden_states,
   (...)
    604         use_reentrant=False
    605     )
    606 else:
--> 607     layer_ret = layer(
    608         hidden_states,
    609         attention_mask,
    610         rotary_pos_emb,
    611         kv_cache=kv_caches[index],
    612         use_cache=use_cache
    613     )
    614 hidden_states, kv_cache = layer_ret
    615 if use_cache:
    616     # token by token decoding, use tuple format

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File ~/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py:510, in GLMBlock.forward(self, hidden_states, attention_mask, rotary_pos_emb, kv_cache, use_cache)
    508 layernorm_output = self.input_layernorm(hidden_states)
    509 # Self attention.
--> 510 attention_output, kv_cache = self.self_attention(
    511     layernorm_output,
    512     attention_mask,
    513     rotary_pos_emb,
    514     kv_cache=kv_cache,
    515     use_cache=use_cache
    516 )
    518 # Residual connection.
    519 if self.apply_residual_connection_post_layernorm:

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File ~/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py:376, in SelfAttention.forward(self, hidden_states, attention_mask, rotary_pos_emb, kv_cache, use_cache)
    374 # adjust key and value for inference
    375 if kv_cache is not None:
--> 376     cache_k, cache_v = kv_cache
    377     key_layer = torch.cat((cache_k, key_layer), dim=2)
    378     value_layer = torch.cat((cache_v, value_layer), dim=2)

ValueError: too many values to unpack (expected 2)

**Comment by luoki7** [comment]
遇到了类似的问题:
Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 1005, in forward
    transformer_outputs = self.transformer(
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 901, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 726, in forward
    layer_ret = layer(
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 629, in forward
    attention_output, kv_cache = self.self_attention(
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/onethingai-fs/ai/GLM-4/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 494, in forward
    cache_k, cache_v = kv_cache
ValueError: too many values to unpack (expected 2)

**Comment by spunk166** [comment]
严格按照：
`modelscope==1.9.5
transformers==4.40.0
streamlit==1.24.0
sentencepiece==0.1.99
accelerate==0.29.3
datasets==2.13.0
peft==0.10.0
tiktoken==0.7.0`  这依赖包，就没问题，主要是transformers 的版本不能高于4.40.0

**Comment by ytWu1314** [comment]
> 感谢大佬，问题已解决

> > 尝试一下使用教程推荐的环境镜像吧，可能是其他什么环境问题了
> 
> 使用环境镜像报错 ：TypeError: peft.peft_model.PeftModelForCausalLM.generate() argument after ** must be a mapping, not Tensor

大佬您咋解决的？我是完全按照教程的镜像然后报错：

Keyword arguments {'return_dict': True} not recognized.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 28
     26 gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
     27 with torch.no_grad():
---> 28     outputs = model.generate(**inputs, **gen_kwargs)
     29     outputs = outputs[:, inputs['input_ids'].shape[1]:]
     30     print(tokenizer.decode(outputs[0], skip_special_tokens=True))

TypeError: peft.peft_model.PeftModelForCausalLM.generate() argument after ** must be a mapping, not Tensor

重新安装了 https://github.com/datawhalechina/self-llm/issues/198#issuecomment-2225015521
👆这个大佬的我也还是报错： too many values to unpack
