### ISSUE TITLE
GLM-4-9B-chat微调部分运行至加载lora权重推理处报错value error

### ISSUE THREAD

**Issue by Eric374254** [datawhalechina/self-llm#199]
运行环境cuda:11.8.0 python:3.9 torch 2.1.1
参照glam-4的微调部分，前面部分运行基本正常，直到加载lora权重推理一步报错，完整报错如下
![图像](https://github.com/datawhalechina/self-llm/assets/154628417/95ac859d-65e6-4214-93e0-c09588e60a9b)

**Comment by KMnO4-zx** [comment]
最后一步 需要重启notebook 单独运行

**Comment by Eric374254** [comment]
感谢大佬

**Comment by Eric374254** [comment]
最后一步重启notebook之后仍旧报一样的错，重启之后仅在装完需要的包之后运行了最后一步的cell

**Comment by KMnO4-zx** [comment]
尝试一下使用教程推荐的环境镜像吧，可能是其他什么环境问题了

**Comment by Eric374254** [comment]
大佬，我目前用的最新的环境torch和python都能和教程里的对上，但是cuda只有11.8，换用python3.10之后，在原有加载内容之前有这样一段提示：
Could not load bitsandbytes native library: libcusparse.so.11: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 109, in <module>
    lib = get_native_library()
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 96, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

CUDA Setup failed despite CUDA being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

**Comment by KMnO4-zx** [comment]
最好用cuda12.1叭，现在大模型对好多不支持11.8了

**Comment by Eric374254** [comment]
怀疑是在安装pytorch的时候将compute platform选成了cuda11.8因此导致无法运行教程之中的代码

**Comment by SunJINM** [comment]
transformers版本过高导致的，最好不高于4.40.0

**Comment by xu-peng-7** [comment]
> 尝试一下使用教程推荐的环境镜像吧，可能是其他什么环境问题了

使用环境镜像报错 ：TypeError: peft.peft_model.PeftModelForCausalLM.generate() argument after ** must be a mapping, not Tensor

**Comment by ytWu1314** [comment]
> > 尝试一下使用教程推荐的环境镜像吧，可能是其他什么环境问题了
> 
> 使用环境镜像报错 ：TypeError: peft.peft_model.PeftModelForCausalLM.generate() argument after ** must be a mapping, not Tensor

大佬您解决了吗？我也是完全按照教程然后报错：

Keyword arguments {'return_dict': True} not recognized.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[22], line 28
     26 gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
     27 with torch.no_grad():
---> 28     outputs = model.generate(**inputs, **gen_kwargs)
     29     outputs = outputs[:, inputs['input_ids'].shape[1]:]
     30     print(tokenizer.decode(outputs[0], skip_special_tokens=True))

TypeError: peft.peft_model.PeftModelForCausalLM.generate() argument after ** must be a mapping, not Tensor

重新安装了 https://github.com/datawhalechina/self-llm/issues/198#issuecomment-2225015521
👆这个大佬的我也还是报错： too many values to unpack
