### ISSUE TITLE
采用多张显卡进行GLM-4微调时报错RuntimeError

### ISSUE THREAD

**Issue by Eric374254** [datawhalechina/self-llm#203]
运行至trainer.train()一行的时候报错，完整内容为：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by shutter-cp** [comment]
> 运行至trainer.train()一行时报错，完整内容为：RuntimeError：预计所有张量都在同一设备上，但发现至少两个设备，cuda:0和cuda:1！

是解决了吗？如何解决的？我同样遇到这个问题了
