### ISSUE TITLE
最重要的保存你是没写啊

### ISSUE THREAD

**Issue by chinlee1523** [datawhalechina/self-llm#212]
https://github.com/datawhalechina/self-llm/blob/master/Qwen2/05-Qwen2-7B-Instruct%20Lora%20%E5%BE%AE%E8%B0%83.md
trainer.save_model("./output/Qwen2-7B-Instruct")

**Comment by KMnO4-zx** [comment]
![image](https://github.com/user-attachments/assets/1403ad5e-4a50-443b-ac3a-6556f8cf5e22)
训练的时候会自动保存的
