### ISSUE TITLE
”02-Gemma-2-9b-it langchain 接入“章节README中最后的使用案例应该使用Gemma模型

### ISSUE THREAD

**Issue by w251510860** [datawhalechina/self-llm#234]
按照本章的内容连续性来讲，应该使用

`llm = Gemma2_LLM('/root/autodl-tmp/LLM-Research/gemma-2-9b-it')`
而不是
`
llm = Yuan2_LLM('/root/autodl-fs/YuanLLM/Yuan2-2B-Mars-hf')
`

当然，也可以下载Yuan2-2B-Mars-hf模型进行加载。

**Comment by KMnO4-zx** [comment]
额？我没看出来有啥不同呀?这不是换了个路径吗？

**Comment by KMnO4-zx** [comment]
好的，收到！

**Comment by KMnO4-zx** [comment]
已修改，感谢提醒~
