### ISSUE TITLE
使用fastapi 的GLM4.    出现 AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'stream_generate'. Did you mean: 'can_generate'?

### ISSUE THREAD

**Issue by triumph** [datawhalechina/self-llm#239]
使用fastapi 的GLM4.    出现 
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'stream_generate'. Did you mean: 'can_generate'?

好像是GLM4 最近升级， 请问我们需要怎么修改下呢？ 谢谢大佬

**Comment by YANGLEDUO1** [comment]
解决了吗

**Comment by daydayfantasy** [comment]
解决了吗
