### ISSUE TITLE
ChatGLM3的lora微调问题

### ISSUE THREAD

**Issue by zhangmaohong** [datawhalechina/self-llm#26]
1、loss下降过快，但是没有定位到原因，训练结束也没有生成新的模型文件
![loss异常](https://github.com/datawhalechina/self-llm/assets/26495548/810caaaa-73c1-4b9e-a513-1dd78acdb435)
2、前面都能泡通，模型推理会抱错，但估计也是模型文件没有真正生成的原因导致的

**Comment by Hongru0306** [comment]
请问用的是repo里面的数据吗？还是自己的数据？

**Comment by zhangmaohong** [comment]
用的repo嬛嬛那个数据集

**Comment by Hongru0306** [comment]
您好，我这边刚拉下来跑完，没有出现问题:  
![image](https://github.com/datawhalechina/self-llm/assets/99795077/c5a4ab8d-3ad8-42d9-9abf-e918c70e8fb1)
LoRa微调本身就是不保存权重的，它只保存lora微调的部分，加载的时候需要peft进行二者一起加载，细节可参考同目录下的md文件:  
![image](https://github.com/datawhalechina/self-llm/assets/99795077/f91dc451-fadc-47de-acd7-77ff71ba262c)

**Comment by zhangmaohong** [comment]
我之前都是在notebook里面跑的 现在跑的py文件还是一样呢
<img width="674" alt="image" src="https://github.com/datawhalechina/self-llm/assets/26495548/13986791-7165-42d6-8e42-e4ee4beaf4b4">

**Comment by KMnO4-zx** [comment]
你应该是前面的某一步搞错了，我们这边复现的结果loss是逐步下降的。请检查你之前的步骤。

**Comment by sjy** [comment]
我也遇到了一样的问题，按照文档跑的，loss 没有下降

**Comment by rxy1212** [comment]
我出现了跟楼主一样的问题，也是loss变成了0.0，也没有生成模型文件

**Comment by rxy1212** [comment]
将 peft 降级至 0.6.2 可以解决问题

**Comment by zjk000** [comment]
你好请问一下你训练完之后是如何保存lora的权重到本地的？
```
llm = AutoModelForCausalLM.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda()
model = get_peft_model(llm, lora_config).cuda()
model.save_pretrained("trained_lora_weights")
```
请问是使用类似上述的代码保存的吗？我这么写有问题吗？为什么无法保存lora权重到本地？
