### ISSUE TITLE
AutoDL的llama3环境镜像transformers版本需要更新

### ISSUE THREAD

**Issue by HackerGary** [datawhalechina/self-llm#268]
运行Chat-嬛嬛train.py报错：valueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
原因：transformers版本需要更新
解决：运行pip install --upgrade transformers即可

**Comment by KMnO4-zx** [comment]
好的，收到！
