### ISSUE TITLE
lora微调 没有用peft_model包装base pre train model

### ISSUE THREAD

**Issue by MXD6** [datawhalechina/self-llm#277]
[LLaMA3-8B-Instruct Lora 微调](https://github.com/datawhalechina/self-llm/blob/master/models/LLaMA3/04-LLaMA3-8B-Instruct%20Lora%20%E5%BE%AE%E8%B0%83.md)
定义好lora_config后，为什么没有get_peft_model，Trainer传入的是pretrain model.
```python
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized_id,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)
trainer.train()
```

**Comment by KMnO4-zx** [comment]
在notebook代码演示文件中有写哦
