### ISSUE TITLE
小白不懂本地部署

### ISSUE THREAD

**Issue by belo-belove** [datawhalechina/self-llm#278]
我部署完大模型了pycharm远程控制老是出现
![image](https://github.com/user-attachments/assets/aefcd5dd-483d-4962-bb8d-634981a1303e)
![屏幕截图 2024-11-13 232812](https://github.com/user-attachments/assets/e10ab129-ef53-4cff-870f-a3a7c5fe7841)
zhe这个报错有解决方法吗

**Comment by KMnO4-zx** [comment]
你可以尝试以下步骤来解决这个问题：

1. 检查 PyCharm 的远程配置设置，确保配置正确。
2. 确认远程服务器的 SSH 服务正常运行，并且可以通过其他 SSH 客户端连接。
3. 查看错误日志，找出具体的错误信息，针对性地解决问题。
4. 如果问题依然存在，可以在 Issue 中附上详细的错误日志和配置截图，方便其他开发者提供帮助。
