### ISSUE TITLE
想问下torch要什么版本的最好啊

### ISSUE THREAD

**Issue by jole878788** [datawhalechina/self-llm#28]

**Comment by KMnO4-zx** [comment]
torch 2.0 版本以上 最好叭~ torch是向下支持的~

**Comment by jole878788** [comment]
thx～

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 不要葱姜蒜 ***@***.***>
发送时间: Tuesday, January 9, 2024 9:17:58 PM
收件人: datawhalechina/self-llm ***@***.***>
抄送: Jiashu Li ***@***.***>; Author ***@***.***>
主题: Re: [datawhalechina/self-llm] 想问下torch要什么版本的最好啊 (Issue #28)


torch 2.0 版本以上 最好叭~ torch是向下支持的~

―

**Comment by KMnO4-zx** [comment]
客气啦~
