### ISSUE TITLE
想问一下"Half" 类型没有实现 "addmm_impl_cpu_" 操作，这问题怎么解决

### ISSUE THREAD

**Issue by jole878788** [datawhalechina/self-llm#29]
这是在项目ChatGLM-6B中出现的问题，
```from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
# 使用模型下载到的本地路径以加载
model_dir = '/tmp/autodl-tmp/ZhipuAI/chatglm3-6b' #这里我将root改成tmp
# 分词器的加载，本地加载，trust_remote_code=True设置允许从网络上下载模型权重和相关的代码
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
# 模型加载，本地加载，使用AutoModelForCausalLM类
model = AutoModelForCausalLM.from_pretrained(model_dir, trust_remote_code=True)
# 将模型移动到GPU上进行加速（如果有GPU的话）
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
# 使用模型的评估模式来产生对话
model.eval()
# 第一轮对话 
response, history = model.chat(tokenizer, "你好", history=[])     #code的问题出在这里
print(response)
```
想请问一下，是否要将数据类型修改

**Comment by KMnO4-zx** [comment]
您好，可以更详细的描述一下您的问题嘛？没太明白您想要表达什么意思。是想要用在加载的时候选择半精度加载嘛？

---期待您的回复~

**Comment by jole878788** [comment]
这个是报错情况
```
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```
应该是不支持半精度吧

**Comment by KMnO4-zx** [comment]
是在autodl的环境嘛？还是在本地windows环境下报错的？

**Comment by jole878788** [comment]
在autodl上的，我是在学校公用的linux服务器上搭建的

**Comment by KMnO4-zx** [comment]
在自己的服务器上的嘛？

**Comment by KMnO4-zx** [comment]
晚上我在autodl的机器上测试一下，看能不能复现报错。

**Comment by Hongru0306** [comment]
反馈问题的时候，要**注明出现问题的脚本名称**，**报错的具体行或代码块**，**描述好你已经做的操作**，并附录**完整的报错信息**。否则这样模糊的描述也会让开发者困扰。

**Comment by jole878788** [comment]
好的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 不要葱姜蒜 ***@***.***>
发送时间: Wednesday, January 10, 2024 6:12:29 PM
收件人: datawhalechina/self-llm ***@***.***>
抄送: Jiashu Li ***@***.***>; Author ***@***.***>
主题: Re: [datawhalechina/self-llm] 想问一下"Half" 类型没有实现 "addmm_impl_cpu_" 操作，这问题怎么解决 (Issue #29)


  *   我这边在autodl上跟着教程复现没啥问题，没有遇到你的bug。
  *   建议使用和教程相同的环境哦~

image.png (view on web)<https://github.com/datawhalechina/self-llm/assets/77671993/d52ad087-2cf6-4336-aab4-17ccfd154b39>

行的，麻烦您了

―

**Comment by jole878788** [comment]
这里再说一下，发现问题了，没有连上GPU，自己的CPU无法进行半精度计算。

**Comment by pearlzy** [comment]
> 这里再说一下，发现问题了，没有连上GPU，自己的CPU无法进行半精度计


> Author

请问你知道怎么连GPU了嘛 我也出现了这样的问题，我都是按照教程部署的
