### ISSUE TITLE
AutoDL平台Qwen2.5的环境镜像报错

### ISSUE THREAD

**Issue by netAir** [datawhalechina/self-llm#290]
AutoDL平台Qwen2.5的环境镜像报错，试了fastAPI与nstruct Langchain 接入一样的问题
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by KMnO4-zx** [comment]
这里报错应该是显卡设置了双卡，而正常应该是单卡的

**Comment by netAir** [comment]
请问大佬，我申请的机器是单卡的规格，这里看到的也是一张卡。
您说的设置了双卡是哪里的设置呢，我去排查下，多谢。
![屏幕截图 2024-04-23 200506](https://github.com/user-attachments/assets/592ab79b-7206-4afc-9448-985bf2333d4f)

**Comment by KMnO4-zx** [comment]
你具体是看的哪个教程文档部署出错了呢？再者就是qwen2.5-7b模型的bf16半精度部署至少需要15G显存，你现在租的这张卡是不足以部署整个模型的。建议使用3090或者4090

**Comment by netAir** [comment]
是的《Qwen2.5-7B-Instruct FastApi 部署调用》教程，不过我重新申请了一个同规格的实例就可以了。
感谢大佬的答复，十分感谢！
