### ISSUE TITLE
关于没有GPU的情况咨询（队友呢?救一下）

### ISSUE THREAD

**Issue by 912100012** [datawhalechina/self-llm#292]
有一台4G4H8M服务器，没有GPU，如果我不需要微调的情况下，只是想部署API接口供外部使用。
这种场景可以实现吗？会特别特别慢吗？还是压根跑不起来？
如果不可以，那么租GPU的费用会不会比直接调用GPT的费用还要昂贵了呢？这个问题怎么解决呢？
烦请了解的小伙伴救一下。

**Comment by KMnO4-zx** [comment]
那你可以直接用国内厂商做好的api接口啊，比如deepseek
