### ISSUE TITLE
自定义视觉模型和语言模型组合

### ISSUE THREAD

**Issue by ander008** [datawhalechina/self-llm#295]
哇！！！！好项目！！！请问有没有将语言模型和视觉模型结合的教程呀？或者后面有没有规划呢？我想自己修改视觉模型里的模块或者语言模型里的模块，再结合起来，进行微调。期待作者您的回复或者建议，谢谢啦！！！

**Comment by KMnO4-zx** [comment]
感谢支持！关于语言模型和视觉模型的结合，目前常用的方法是使用预训练的大语言模型作为基础，通过一个视觉模型（如ViT）将图像转为token，再将视觉token与语言token结合后进行微调。这种方式支持模块化组合，可以自由选择不同的语言和视觉模型，只需设计适配层即可。推荐参考开源项目如BLIP、CLIP或LLaVA。

未来我们计划制作关于语言模型与视觉模型结合的相关教程。如果您对这个项目感兴趣并希望参与，欢迎随时通过邮件联系我们～😊

**Comment by ander008** [comment]
感谢回复和建议！希望这个项目越来越好！！
