### ISSUE TITLE
Qwen/07-Qwen-7B-Chat 接入langchain搭建知识库助手不支持多轮对话该如何优化代码呢

### ISSUE THREAD

**Issue by sweetboxwwy** [datawhalechina/self-llm#30]

**Comment by logan-zou** [comment]
为便于学习者理解，此处我们选用了不带历史对话的检索链，如果想要支持多轮对话，可以使用 LangChain 中支持历史记录的检索链，更多细节可以查阅 Datawhale 的另一门开源课程《动手学大模型应用开发》
