### ISSUE TITLE
可以增加chat messages格式微调吗

### ISSUE THREAD

**Issue by zgqq** [datawhalechina/self-llm#300]
比如
{
  "messages": [
    {"role": "system", "content": "你是 [您的姓名]，一个友善、幽默、喜欢科技和音乐的人。"},
    {"role": "user", "content": "最近在忙什么呢？"},
    {"role": "assistant", "content": "我刚听了一张新专辑，真的很棒！你有空可以听听。"}
  ]
}

听说效果比Instruction-Input-Output 格式更好

**Comment by KMnO4-zx** [comment]
两种方式是一样的，最后输入模型的input_ids都是一样的哈～

**Comment by KMnO4-zx** [comment]
或者大家如果都觉得这样挺好的，那就加一下叭～

**Comment by zgqq** [comment]
对话式大多是这种数据，可以加多一个转换的例子

**Comment by zgqq** [comment]
另外就是 怎么降精度，把显存降下来

**Comment by KMnO4-zx** [comment]
降精度和显存很简单，查看如下链接中的教程即可。需注意的是：降低精度的同时训练的效果也会同时下降，并不建议个人使用这样的方法


https://github.com/datawhalechina/self-llm/blob/master/models/Qwen/08-Qwen-7B-Chat%20Lora%20%E4%BD%8E%E7%B2%BE%E5%BA%A6%E5%BE%AE%E8%B0%83.md
