### ISSUE TITLE
如果想尝试一下其他的微调方法，比如adalora、H-adapter之类的有可以参考的嘛～

### ISSUE THREAD

**Issue by jingtian11** [datawhalechina/self-llm#306]

**Comment by KMnO4-zx** [comment]
可以看HF PEFT的官方文档，其中有很多种高效微调方式，如下图所示：
文档链接：https://huggingface.co/docs/peft/index

![image](https://github.com/user-attachments/assets/c94bad47-ffe2-4697-bcf9-824da8d832c5)

**Comment by KMnO4-zx** [comment]
只需要简单的替换即可

**Comment by jingtian11** [comment]
好的感谢
