### ISSUE TITLE
Qwen中的FastAPI部署部分代码可否优化？

### ISSUE THREAD

**Issue by pengrui-art** [datawhalechina/self-llm#307]
async def create_item(request: Request):
    global model, tokenizer
    json_post_list = await request.json()
    # json_post = json.dumps(json_post_raw)
    # json_post_list = json.loads(json_post)
注释部分可以省去，因为request.json()返回的已经是一个字典，感觉没有必要来回转换

**Comment by KMnO4-zx** [comment]
可以优化吖，这只是一个简单的示例代码~
