### ISSUE TITLE
纯小白，按照教程来的，为什么打开6006端口显示“拒绝了我们的连接请求。”有哪位同学知道什么原因吗？

### ISSUE THREAD

**Issue by du2279664786** [datawhalechina/self-llm#31]
![image](https://github.com/datawhalechina/self-llm/assets/76576534/24634e69-736f-4c3e-8b1d-def9025b85fb)

**Comment by KMnO4-zx** [comment]
请看这个issue： https://github.com/datawhalechina/self-llm/issues/27
