### ISSUE TITLE
可以出一些moe-lora的教程么

### ISSUE THREAD

**Issue by wzProspective** [datawhalechina/self-llm#312]
可以出一些qwen与moe-lora的教程么

**Comment by KMnO4-zx** [comment]
目前是有Qwen的微调和moe的微调的哈，moe和dense模型在微调上区别不大~

![image](https://github.com/user-attachments/assets/449ff77c-62d9-4667-9780-6d8f716ae200)

![image](https://github.com/user-attachments/assets/ac447782-e6f0-4f17-9dda-873fa7dfec90)

**Comment by wzProspective** [comment]
谢谢您的解答，就是今年涌现了一些将moe架构融入lora的微调方法，在解决多任务方面具有较好的表现，能出一个这个的教程嘛，谢谢。

**Comment by KMnO4-zx** [comment]
研究性质的教程 不会出现在本项目中哈~你可以自己学习一下~

**Comment by KMnO4-zx** [comment]
目前没有这个ToDo，但你可以来Datawhale公众号的“**_有求必应_**”专区许愿这个教程！
