### ISSUE TITLE
04-ChatGLM3-6B-Code-Interpreter.md运行报错

### ISSUE THREAD

**Issue by chen960** [datawhalechina/self-llm#32]
在执行ChatGLM的04-ChatGLM3-6B-Code-Interpreter.md时，

`streamlit run /root/autodl-tmp/ChatGLM3/composite_demo/main.py --server.address 127.0.0.1 --server.port 6006`

在运行这一行代码后，通过127.0.0.1:6006进入前端界面后会出现下边这张截图的错误。
![image](https://github.com/datawhalechina/self-llm/assets/35607059/698ab242-bf3a-4e9a-9686-d693a076f1d9)

**Comment by KMnO4-zx** [comment]
请详细描述一下你的问题

**Comment by chen960** [comment]
> 请详细描述一下你的问题

抱歉，已更新问题描述。

**Comment by chen960** [comment]
搞明白原因了，当前环境是python3.8，python3.10才引入match命令，所以报错了

**Comment by KMnO4-zx** [comment]
> 搞明白原因了，当前环境是python3.8，python3.10才引入match命令，所以报错了

好的
