### ISSUE TITLE
Qwen/04-Qwen-7B-Chat Lora 微调报错TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

### ISSUE THREAD

**Issue by Dreamshe-92** [datawhalechina/self-llm#34]
按照指引按照了对应第三方库的版本
跑对应脚本报错

The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.56s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data2/py/demo/fin_demo.py:76 in <module>                                                  │
│                                                                                                  │
│   73 │   │   train_dataset=tokenized_id,                                                         │
│   74 │   │   data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),            │
│   75 │   │   )                                                                                   │
│ ❱ 76 │   trainer.train() # 开始训练                                                              │
│   77 │   response, history = model.chat(tokenizer, "你是谁", history=[], system="现在你要扮演    │
│   78 │   print(response)                                                                         │
│   79                                                                                             │
│                                                                                                  │
│ /data2/py/lib/python3.9/site-packages/transformers/trainer.py:1555 in train                │
│                                                                                                  │
│   1552 │   │   │   finally:                                                                      │
│   1553 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1554 │   │   else:                                                                             │
│ ❱ 1555 │   │   │   return inner_training_loop(                                                   │
│   1556 │   │   │   │   args=args,                                                                │
│   1557 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1558 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /data2/py/lib/python3.9/site-packages/transformers/trainer.py:1668 in _inner_training_loop │
│                                                                                                  │
│   1665 │   │   │   else:                                                                         │
│   1666 │   │   │   │   gradient_checkpointing_kwargs = args.gradient_checkpointing_kwargs        │
│   1667 │   │   │                                                                                 │
│ ❱ 1668 │   │   │   self.model.gradient_checkpointing_enable(gradient_checkpointing_kwargs=gradi  │
│   1669 │   │                                                                                     │
│   1670 │   │   model = self._wrap_model(self.model_wrapped)                                      │
│   1671                                                                                           │
│                                                                                                  │
│ /data2/py/lib/python3.9/site-packages/transformers/modeling_utils.py:1872 in               │
│ gradient_checkpointing_enable                                                                    │
│                                                                                                  │
│   1869 │   │                                                                                     │
│   1870 │   │   gradient_checkpointing_func = functools.partial(checkpoint, **gradient_checkpoin  │
│   1871 │   │                                                                                     │
│ ❱ 1872 │   │   self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradie  │
│   1873 │   │                                                                                     │
│   1874 │   │   if getattr(self, "_hf_peft_config_loaded", False):                                │
│   1875 │   │   │   # When using PEFT + gradient checkpointing + Trainer we need to make sure th  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

**Comment by KMnO4-zx** [comment]
gradient_checkpointing：梯度检查，这个一旦开启，模型就必须执行model.enable_input_require_grads()方法哦~

请检查加载模型之后是否执行这个方法

**Comment by Dreamshe-92** [comment]
这边是按照04-Qwen-7B-Chat Lora 微调.py的脚本没修改跑的，就是需要将gradient_checkpointing设置为False？

# 配置训练参数
args = TrainingArguments(
    output_dir="./output/Qwen",
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    logging_steps=10,
    num_train_epochs=3,
    gradient_checkpointing=True,
    save_steps=100,
    learning_rate=1e-4,
    save_on_each_node=True
)

**Comment by KMnO4-zx** [comment]
如果开启gradient_checkpointing，那就需要执行model.enable_input_require_grads()方法，如果不开启gradient_checkpointing微调所需要的显存大概在30G左右
