### ISSUE TITLE
已经安装accelerate库，但是一直提示找不到

### ISSUE THREAD

**Issue by CharlieZZss** [datawhalechina/self-llm#35]
在chatGLM的Lora微调教程里，原步骤是这样
![屏幕截图 2024-01-26 221052](https://github.com/datawhalechina/self-llm/assets/101547157/86d1e3d8-0601-4c41-a578-89e06f5755da)

已经安装accelerate库，import也不报错
![image](https://github.com/datawhalechina/self-llm/assets/101547157/9971b29a-8be1-4340-aff0-811eec1f0cdc)

但是创建模型时报错找不到accelerate
![image](https://github.com/datawhalechina/self-llm/assets/101547157/74b6978a-7cb2-45d0-b595-76b1b1f18edf)
应该也不是安装路径问题？因为一起安装的peft等其他库调用没有问题

**Comment by KMnO4-zx** [comment]
执行一下：pip show accelerate
看看有没有安装

其次，可以尝试重启一下notebook，或者重启一下实例

**Comment by CharlieZZss** [comment]
![image](https://github.com/datawhalechina/self-llm/assets/101547157/13e8ed2b-36fa-41c7-a934-baf7304a19b2)
已经安装了，执行完是这个样子的。已经换过好几个实例都是这样

**Comment by Hongru0306** [comment]
您好，可以先将low_cpu这里注释掉，看能不能加载。

**Comment by CharlieZZss** [comment]
好的已解决，彻底换了实例重新配了一遍环境

**Comment by dbblzy** [comment]
/home/xxxx/.local/bin/accelerate launch 先pip show出来位置 ，直接从这个位置启动
