### ISSUE TITLE
chatGLM模型训练后，得到的微调结果和示例不一样

### ISSUE THREAD

**Issue by CharlieZZss** [datawhalechina/self-llm#36]
![image](https://github.com/datawhalechina/self-llm/assets/101547157/37a6a02b-c728-4a90-9cef-5e6c874ee4d5)
示例里，微调的参数在模型输出路径文件夹下的checkpoint-1000文件夹中。按照示例的微调方法运行之后，微调结果输出路径不同，为runs/Jan27_01-06-17_autodl-container-049a448514-394ad272/，其中文件也不同。
![image](https://github.com/datawhalechina/self-llm/assets/101547157/504aaf85-4849-44a8-9258-63bf5cef926c)
![image](https://github.com/datawhalechina/self-llm/assets/101547157/e32b2df1-a8cd-4606-9c32-fa36a6af2bf3)
请问这里该怎么处理

**Comment by AHPUymhd** [comment]
> ![image](https://private-user-images.githubusercontent.com/101547157/300063840-37a6a02b-c728-4a90-9cef-5e6c874ee4d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDYzODQwLTM3YTZhMDJiLWM3MjgtNGE5MC05Y2VmLTVlNmM4NzRlZTRkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGJmODBjYjdlOGZmMzRhNWM5NDRmZjZlZDI0YjhkMjlmMjVlMjU5ZGZkNDhlNGE3NmE5NzJiOTVlN2E3ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EOOjCdVEBEaXSsrk43UsvTUNUbLmDTHFJw6BpkDFCDE) 示例里，微调的参数在模型输出路径文件夹下的checkpoint-1000文件夹中。按照示例的微调方法运行之后，微调结果输出路径不同，为runs/Jan27_01-06-17_autodl-container-049a448514-394ad272/，其中文件也不同。 ![image](https://private-user-images.githubusercontent.com/101547157/300066363-504aaf85-4849-44a8-9258-63bf5cef926c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDY2MzYzLTUwNGFhZjg1LTQ4NDktNDRhOC05MjU4LTYzYmY1Y2VmOTI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODZjYmU3MmYxYWFkODAzMTExNDhkNzU4MzE0YTIyOWU0MDNhODhhYTllNjg1Y2E1ZjQ2NDc5ZjA1NTFhMTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmkgCyZ2CyObYKM3lEDaBgRKEgfn3s4TiTLjppL-xR0) ![image](https://private-user-images.githubusercontent.com/101547157/300066529-e32b2df1-a8cd-4606-9c32-fa36a6af2bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDY2NTI5LWUzMmIyZGYxLWE4Y2QtNDYwNi05YzMyLWZhMzZhNmFmMmJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWJiYjMxYTU4NjE1YjJlYThkMWNhNGE4OGZlMmMwYWIxNmM4NGUzYTZiYTQ1OWFhYWI3ZDc4NGRmOGVjZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IitxkkE0cd6IFo7tqaPCP25dfKRrgRtCmkRPUECTpZo) 请问这里该怎么处理

请问您最后解决了吗，我也遇到这个问题了

**Comment by CharlieZZss** [comment]
> > ![image](https://private-user-images.githubusercontent.com/101547157/300063840-37a6a02b-c728-4a90-9cef-5e6c874ee4d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDYzODQwLTM3YTZhMDJiLWM3MjgtNGE5MC05Y2VmLTVlNmM4NzRlZTRkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGJmODBjYjdlOGZmMzRhNWM5NDRmZjZlZDI0YjhkMjlmMjVlMjU5ZGZkNDhlNGE3NmE5NzJiOTVlN2E3ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EOOjCdVEBEaXSsrk43UsvTUNUbLmDTHFJw6BpkDFCDE) 示例里，微调的参数在模型输出路径文件夹下的checkpoint-1000文件夹中。按照示例的微调方法运行之后，微调结果输出路径不同，为runs/Jan27_01-06-17_autodl-container-049a448514-394ad272/，其中文件也不同。 ![image](https://private-user-images.githubusercontent.com/101547157/300066363-504aaf85-4849-44a8-9258-63bf5cef926c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDY2MzYzLTUwNGFhZjg1LTQ4NDktNDRhOC05MjU4LTYzYmY1Y2VmOTI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODZjYmU3MmYxYWFkODAzMTExNDhkNzU4MzE0YTIyOWU0MDNhODhhYTllNjg1Y2E1ZjQ2NDc5ZjA1NTFhMTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmkgCyZ2CyObYKM3lEDaBgRKEgfn3s4TiTLjppL-xR0) ![image](https://private-user-images.githubusercontent.com/101547157/300066529-e32b2df1-a8cd-4606-9c32-fa36a6af2bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDY2NTI5LWUzMmIyZGYxLWE4Y2QtNDYwNi05YzMyLWZhMzZhNmFmMmJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWJiYjMxYTU4NjE1YjJlYThkMWNhNGE4OGZlMmMwYWIxNmM4NGUzYTZiYTQ1OWFhYWI3ZDc4NGRmOGVjZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IitxkkE0cd6IFo7tqaPCP25dfKRrgRtCmkRPUECTpZo) 请问这里该怎么处理
> 
> 请问您最后解决了吗，我也遇到这个问题了

我的微调参数是这样设置的：
data_collator = DataCollatorForSeq2Seq(
    tokenizer,
    model=model,
    label_pad_token_id=-100,
    pad_to_multiple_of=None,
    padding=False
)
args = TrainingArguments(
    output_dir="/root/autodl-tmp/huan_dataset/output",#相对路径无法生成check-points文件夹
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    logging_steps=5,
    num_train_epochs=1,
    save_strategy='steps',
    save_steps=10,
    learning_rate=1e-4,
    #gradient_checkpointing=True,这句解开会报错
)
加载微调后模型的代码是这样的：
from peft import PeftModel
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForSeq2Seq, TrainingArguments, Trainer
import torch
tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/ZhipuAI/chatglm3-6b", use_fast=False, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("/root/autodl-tmp/ZhipuAI/chatglm3-6b", trust_remote_code=True, low_cpu_mem_usage=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
p_model = PeftModel.from_pretrained(model, model_id="/root/autodl-tmp/huan_dataset/output/checkpoint-400/")  # 将训练所得的LoRa权重加载起来
ipt = tokenizer("<|system|>\n现在你要扮演皇帝身边的女人--甄嬛\n<|user|>\n {}\n{}".format("你是谁？", "").strip() + "<|assistant|>\n", return_tensors="pt").to(model.device)
tokenizer.decode(p_model.generate(**ipt, max_length=128, do_sample=True)[0], skip_special_tokens=True)

**Comment by AHPUymhd** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/101547157/300063840-37a6a02b-c728-4a90-9cef-5e6c874ee4d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDYzODQwLTM3YTZhMDJiLWM3MjgtNGE5MC05Y2VmLTVlNmM4NzRlZTRkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGJmODBjYjdlOGZmMzRhNWM5NDRmZjZlZDI0YjhkMjlmMjVlMjU5ZGZkNDhlNGE3NmE5NzJiOTVlN2E3ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EOOjCdVEBEaXSsrk43UsvTUNUbLmDTHFJw6BpkDFCDE) 示例里，微调的参数在模型输出路径文件夹下的checkpoint-1000文件夹中。按照示例的微调方法运行之后，微调结果输出路径不同，为runs/Jan27_01-06-17_autodl-container-049a448514-394ad272/，其中文件也不同。 ![image](https://private-user-images.githubusercontent.com/101547157/300066363-504aaf85-4849-44a8-9258-63bf5cef926c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDY2MzYzLTUwNGFhZjg1LTQ4NDktNDRhOC05MjU4LTYzYmY1Y2VmOTI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODZjYmU3MmYxYWFkODAzMTExNDhkNzU4MzE0YTIyOWU0MDNhODhhYTllNjg1Y2E1ZjQ2NDc5ZjA1NTFhMTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmkgCyZ2CyObYKM3lEDaBgRKEgfn3s4TiTLjppL-xR0) ![image](https://private-user-images.githubusercontent.com/101547157/300066529-e32b2df1-a8cd-4606-9c32-fa36a6af2bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjg4MzksIm5iZiI6MTcwOTcyODUzOSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDY2NTI5LWUzMmIyZGYxLWE4Y2QtNDYwNi05YzMyLWZhMzZhNmFmMmJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWJiYjMxYTU4NjE1YjJlYThkMWNhNGE4OGZlMmMwYWIxNmM4NGUzYTZiYTQ1OWFhYWI3ZDc4NGRmOGVjZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IitxkkE0cd6IFo7tqaPCP25dfKRrgRtCmkRPUECTpZo) 请问这里该怎么处理
> > 
> > 
> > 请问您最后解决了吗，我也遇到这个问题了
> 
> 我的微调参数是这样设置的： data_collator = DataCollatorForSeq2Seq( tokenizer, model=model, label_pad_token_id=-100, pad_to_multiple_of=None, padding=False ) args = TrainingArguments( output_dir="/root/autodl-tmp/huan_dataset/output",#相对路径无法生成check-points文件夹 per_device_train_batch_size=1, gradient_accumulation_steps=8, logging_steps=5, num_train_epochs=1, save_strategy='steps', save_steps=10, learning_rate=1e-4, #gradient_checkpointing=True,这句解开会报错 ) 加载微调后模型的代码是这样的： from peft import PeftModel from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForSeq2Seq, TrainingArguments, Trainer import torch tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/ZhipuAI/chatglm3-6b", use_fast=False, trust_remote_code=True) model = AutoModelForCausalLM.from_pretrained("/root/autodl-tmp/ZhipuAI/chatglm3-6b", trust_remote_code=True, low_cpu_mem_usage=True) device = torch.device("cuda" if torch.cuda.is_available() else "cpu") model.to(device) p_model = PeftModel.from_pretrained(model, model_id="/root/autodl-tmp/huan_dataset/output/checkpoint-400/") # 将训练所得的LoRa权重加载起来 ipt = tokenizer("<|system|>\n现在你要扮演皇帝身边的女人--甄嬛\n<|user|>\n {}\n{}".format("你是谁？", "").strip() + "<|assistant|>\n", return_tensors="pt").to(model.device) tokenizer.decode(p_model.generate(**ipt, max_length=128, do_sample=True)[0], skip_special_tokens=True)

谢谢好兄弟！！就是请问你直接生成的是checkpoint格式的输出吗，为什么我生成的是events.out.tfevents.1709949130.autodl-container-7d27418359-b92bcb1c.3146.0这种格式的输出，请问可以麻烦贴出您的全部代码吗，我也是按着教程来的啊
