### ISSUE TITLE
chatGLM模型训练后，微调结果没有输出在指定路径里

### ISSUE THREAD

**Issue by CharlieZZss** [datawhalechina/self-llm#37]
![image](https://github.com/datawhalechina/self-llm/assets/101547157/37a6a02b-c728-4a90-9cef-5e6c874ee4d5)
示例里，微调的参数在模型输出路径文件夹下的checkpoint-1000文件夹中。按照示例的微调方法运行之后，没有生成 checkpoints 文件，只有一个runs文件夹。
![image](https://github.com/datawhalechina/self-llm/assets/101547157/f2aee7db-4704-41c4-9180-fc83f8e8ff72)

![image](https://github.com/datawhalechina/self-llm/assets/101547157/d1196f72-0e52-4bd9-9e72-fe4ce64ffed4)
请问这里该怎么处理

**Comment by KMnO4-zx** [comment]
@Hongru0306

**Comment by Hongru0306** [comment]
您好，根据您的问题提供两个解决思路:
- 1.设置一下`save_strategy`,设置成10个step，看看是否能持续输出保存路径。
- 2.将保存路径指定到绝对路径，而不是相对路径。

**Comment by AHPUymhd** [comment]
> ![image](https://private-user-images.githubusercontent.com/101547157/300063840-37a6a02b-c728-4a90-9cef-5e6c874ee4d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTExNjUsIm5iZiI6MTcwOTk1MDg2NSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMDYzODQwLTM3YTZhMDJiLWM3MjgtNGE5MC05Y2VmLTVlNmM4NzRlZTRkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwMjIxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTg4MjBiN2M0NWM4YTg0NTE1OTljNDU2MjZhY2FmZWI1ZjU5ZmM5YzA4ZDk0NjU0ZWZiODIyMmNmZWUxOTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TV1F-mLheq_Xr1SLKZaejCCXu9dN8qY_bLvlWBPAQz4) 示例里，微调的参数在模型输出路径文件夹下的checkpoint-1000文件夹中。按照示例的微调方法运行之后，没有生成 checkpoints 文件，只有一个runs文件夹。 ![image](https://private-user-images.githubusercontent.com/101547157/300161367-f2aee7db-4704-41c4-9180-fc83f8e8ff72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTExNjUsIm5iZiI6MTcwOTk1MDg2NSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMTYxMzY3LWYyYWVlN2RiLTQ3MDQtNDFjNC05MTgwLWZjODNmOGU4ZmY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwMjIxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmVmMWNhMWE5MDY1MjBiYjQ5ZGQ2ZDAyYzg1OGZkN2RjZDUzYjk1NTZmNGUyZmQ5NDFkMTc3ZDYwZjk5MGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8Mu18tptDV_GSvqOL6YuH9K54Qp4MckWH7HwWOUPs4)
> 
> ![image](https://private-user-images.githubusercontent.com/101547157/300161379-d1196f72-0e52-4bd9-9e72-fe4ce64ffed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTExNjUsIm5iZiI6MTcwOTk1MDg2NSwicGF0aCI6Ii8xMDE1NDcxNTcvMzAwMTYxMzc5LWQxMTk2ZjcyLTBlNTItNGJkOS05ZTcyLWZlNGNlNjRmZmVkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwMjIxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2MxZWEwMDQxM2U2ZWNiMjU5NDA3ZTc5YmY3NTA4NmU2NTBkYzY0NDgzMzZkOGNmYjRjMmZiZTU0OTJlYThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CNCxI9A7eIBrqYc2FhzIpSg46K2h_DygtcXTrwoJuTo) 请问这里该怎么处理

我也是这样的，请问您解决了吗
