### ISSUE TITLE
代码笔误pd.read_json('../dataset/huanhuan.jsonl')，应该是pd.read_json('../dataset/huanhuan.json')

### ISSUE THREAD

**Issue by Weihong-Liu** [datawhalechina/self-llm#45]
<img width="863" alt="image" src="https://github.com/datawhalechina/self-llm/assets/65588374/a023aabc-4d0f-405a-a627-99f7040b4bb4">

**Comment by Weihong-Liu** [comment]
这个notebook中有一些作者电脑的绝对路径，应该改成/root/autodl-tmp/xxx
<img width="699" alt="image" src="https://github.com/datawhalechina/self-llm/assets/65588374/4e655123-1a37-4a48-8d38-11f4aad10272">

**Comment by KMnO4-zx** [comment]
好的，感谢~
