### ISSUE TITLE
chatglm搭建知识库读取文件出错

### ISSUE THREAD

**Issue by AHPUymhd** [datawhalechina/self-llm#53]
![image](https://github.com/datawhalechina/self-llm/assets/72792297/25f3a841-4909-4e2a-9e6d-364636c075d4)
如图所示，如果我b不注释上面的那个文件，就会出下面的错误
![image](https://github.com/datawhalechina/self-llm/assets/72792297/9a70108d-f955-4d6f-a093-f2eea5422020)
qi't其他几个文件都可以正常的读取，就这个不行，请问是哪里出了问题呢，我看读取文件的函数感觉也没有问题啊，麻烦您啦

**Comment by KMnO4-zx** [comment]
看上去是因为文件编码不对，不影响注释掉就行

**Comment by AHPUymhd** [comment]
> 看上去是因为文件编码不对，不影响注释掉就行

是滴，但是我看了这几个文件夹感觉都差不多呀，请问哪里的编码出问题了呢
而且还有一个问题就是这个torch没导入的话我电脑会报错
![image](https://github.com/datawhalechina/self-llm/assets/72792297/2ab75c1c-956a-44d4-92c3-98c1382c9e71)

**Comment by KMnO4-zx** [comment]
嗯嗯 这个地方需要在上面导入torch
