### ISSUE TITLE
qwen1.5 量化版本的部署方案有么？

### ISSUE THREAD

**Issue by chongqingwei** [datawhalechina/self-llm#54]
大佬有qwen15的量化版么部署方案。

**Comment by KMnO4-zx** [comment]
本仓库暂时没有，如果有需要的话可以看看vLLM或者LMDeploy

**Comment by byx020119** [comment]
> 大佬有qwen15的量化版么部署方案。

有了，已补充（Qwen1.5-7B-Chat-GPTQ-Int4部署方案 #59  ）

**Comment by KMnO4-zx** [comment]
readme已更新Qwen1.5-72B-chat GPTQ int4 部署链接
