### ISSUE TITLE
想问下部署chatglm出现了问题

### ISSUE THREAD

**Issue by DJzing** [datawhalechina/self-llm#55]
![1709821622232](https://github.com/datawhalechina/self-llm/assets/128670707/5ef309d6-b4ed-46af-8642-eb7405cdef13)

**Comment by KMnO4-zx** [comment]
确定一下模型的地址是否填写正确无误

**Comment by KMnO4-zx** [comment]
确定一下模型的地址是否填写正确无误

**Comment by DJzing** [comment]
没有错误的 我是在autodl上运行 按道理来说是直接读取huggingface的依赖包

**Comment by KMnO4-zx** [comment]
注意看一下这里哦~

![1709904722949](https://github.com/datawhalechina/self-llm/assets/77671993/e492fb22-4f3f-44a4-af77-5e54f17848e7)


https://github.com/datawhalechina/self-llm/blob/master/ChatGLM/02-ChatGLM3-6B%20FastApi%E9%83%A8%E7%BD%B2%E8%B0%83%E7%94%A8.md#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD

**Comment by DJzing** [comment]
已解决 感谢感谢

**Comment by KMnO4-zx** [comment]
好~
