### ISSUE TITLE
Qwen1.5-7B推理部分，为什么我在modelscope上的GPU调试，fastapi报错。

### ISSUE THREAD

**Issue by tking007** [datawhalechina/self-llm#58]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████| 4/4 [00:11<00:00,  2.97s/it]
RuntimeError: asyncio.run() cannot be called from a running event loop

是因为阿里云的环境不支持吗？？

**Comment by KMnO4-zx** [comment]
我们没在阿里云上做过测试，建议使用autodl试一下哦~
