### ISSUE TITLE
deepseek官方readme，loss第二轮开始就是

### ISSUE THREAD

**Issue by liuyongjie985** [datawhalechina/self-llm#63]
如下图

**Comment by liuyongjie985** [comment]
![20240317-001054](https://github.com/datawhalechina/self-llm/assets/12164583/a56d56fc-4079-427b-ac8e-c64e167692eb)

**Comment by KMnO4-zx** [comment]
这是本仓库的教程嘛？如果是deepseek官方仓库的代码的话，还请去deepseek仓库提交issue

**Comment by liuyongjie985** [comment]
是的呀 https://github.com/datawhalechina/self-llm/blob/master/DeepSeek/04-DeepSeek-7B-chat%20Lora%20%E5%BE%AE%E8%B0%83.ipynb

**Comment by liuyongjie985** [comment]
哥哥睡了吗，如果没睡能不能跟着教程试一下，我看了一下代码没发现问题

**Comment by liuyongjie985** [comment]
![abc](https://github.com/datawhalechina/self-llm/assets/12164583/c2f100c3-8f85-4a07-b05a-09cef7d17c44)

**Comment by liuyongjie985** [comment]
哥哥，我调出来了
![kaf](https://github.com/datawhalechina/self-llm/assets/12164583/bb5fad86-1837-444b-b31b-dd9fade3bd9d)
，之前deepseek用的是官方的transformer版本，刚刚想了下教程好像提到了重新装transformer，试了下这下正常，之前inference用的transformer 37，有点害怕啊，明天重新inference下看下效果，看到你回的那么快，心情都好起来了，敬佩，祝好

**Comment by KMnO4-zx** [comment]
好的，数据集不同或者环境不同，包的版本不同，都有可能造成这个情况，也有可能学习率的问题，所以最好和教程一样的环境，比较容易定位问题，哈哈哈，祝你顺利完成学习！
