### ISSUE TITLE
ChatGLM3-6B微调后成哑巴了（字面意思）

### ISSUE THREAD

**Issue by Tangent-90C** [datawhalechina/self-llm#65]
今天按照https://github.com/datawhalechina/self-llm/blob/master/ChatGLM/06-ChatGLM3-6B-Lora%E5%BE%AE%E8%B0%83.md 的教程微调ChatGLM3-6B，结果微调时loss突然归0，后续让微调后的模型回答问题，更是一言不发，一个token都没生成就原样返回……

![image](https://github.com/datawhalechina/self-llm/assets/28804414/cde95aff-431a-43ec-9ff4-fe2ec2e47d79)

Python 3.10.8
相关库的版本：
```
Package                        Version
------------------------------ ---------------
accelerate                     0.28.0
datasets                       2.18.0
peft                           0.9.0
torch                          2.1.2+cu121
transformers                   4.38.2
```

**Comment by KMnO4-zx** [comment]
ChatGLM3模型，仓库文件改动频繁，需要时间定位问题，建议按照本项目readme中的学习建议，优先学习Qwen模型

**Comment by Tangent-90C** [comment]
试了下，peft降级0.6.0就行了

**Comment by KMnO4-zx** [comment]
![image](https://github.com/datawhalechina/self-llm/assets/77671993/1a5b4a94-e5c2-4308-a060-b1b5c0f15f19)
ke'neng'shi可能是高版本兼容性不太好
