### ISSUE TITLE
请问ChatGLM3微调中的数据集huanhuan的在哪获取？

### ISSUE THREAD

**Issue by haory-95** [datawhalechina/self-llm#81]
如题，卡在这一步了，找了半天都没找到这个从哪得到的..sry

**Comment by KMnO4-zx** [comment]
![image](https://github.com/datawhalechina/self-llm/assets/77671993/989d926e-58b6-4a14-a2ff-42b16678e0d9)

**Comment by mlw67** [comment]
数据放在datasets可能不容易被大家发现，建议在本节教程里，我们将微调数据集 `huanhuan.json` 放置在根目录 [/dataset](../dataset/huanhuan.json)，该样本数据取自 [huanhuan.json](https://github.com/datawhalechina/self-llm/blob/master/dataset/huanhuan.json)

**Comment by mlw67** [comment]
数据放在datasets可能不容易被大家发现，建议在本节教程里，我们将微调数据集 huanhuan.json 放置在根目录 [/dataset](https://github.com/datawhalechina/self-llm/dataset/huanhuan.json)，该样本数据取自 [huanhuan.json](https://github.com/datawhalechina/self-llm/blob/master/dataset/huanhuan.json)

**Comment by mlw67** [comment]
数据放在datasets可能不容易被大家发现，建议在本节教程里，通过在对于数据添加链接🔗的方式直接嵌入文档中，
示例：我们将微调数据集 huanhuan.json 放置在根目录中 [/dataset] (https://github.com/datawhalechina/self-llm/dataset/huanhuan.json)，该样本数据也可以自链接下载🔗 [huanhuan.json] (https://github.com/datawhalechina/self-llm/blob/master/dataset/huanhuan.json)

**Comment by haory-95** [comment]
非常感谢你们的耐心解答，眼看花了没注意到dataset这个文件夹，谢谢谢谢
