### ISSUE TITLE
请问LLAMA3，里面是按1.2.3.4的顺序来分别执行吗？

### ISSUE THREAD

**Issue by YadiHe** [datawhalechina/self-llm#94]
我第一个完成后
![image](https://github.com/datawhalechina/self-llm/assets/145848242/fe943e2f-cd57-40a7-8c2b-d5cbc752c3de)
不知道怎么继续对话

**Comment by KMnO4-zx** [comment]
第一个是部署api形式的llama3，第二个是部署langchian接入形式的llama3，第三个是部署webdemo对话，第四个是lora微调llama3.
如果你想要对话的话，可以尝试给第三个

**Comment by YadiHe** [comment]
谢谢指点，请问第二个是部署langchian接入形式的llama3，这里的langchian就是可以接入很多大模型给自己选择用哪一个吗？

**Comment by KMnO4-zx** [comment]
详细内容，请看仓库文档

**Comment by KMnO4-zx** [comment]
https://github.com/datawhalechina/llm-universe

如果你对angchain不太熟悉，可以看下这个仓库

**Comment by YadiHe** [comment]
大佬，在终端中运行以下命令，启动streamlit服务，并按照 autodl 的指示将端口映射到本地，然后在浏览器中打开链接 http://localhost:6006/ ，即可看到聊天界面。
这里怎么打开啊，我到这一步了
![image](https://github.com/datawhalechina/self-llm/assets/145848242/772b031d-9359-4342-84c7-439f6ceb200a)

**Comment by KMnO4-zx** [comment]
https://github.com/datawhalechina/self-llm/blob/master/General-Setting/02-AutoDL%E5%BC%80%E6%94%BE%E7%AB%AF%E5%8F%A3.md

多仔细看下教程文档
